"""
Security Testing Package - CA3
Contains security testing configurations and results
Student: X00203402 - Roko Skugor

This package contains:
- Security scan configurations (.bandit is in root)
- Security test results (generated by pipeline)
- SAST (Static Application Security Testing) outputs
"""