"""
Performance Testing Package - CA3
Contains Locust load testing scripts and results
Student: X00203402 - Roko Skugor

This package contains:
- locustfile.py: Load testing script
- Performance test results (generated by pipeline)
- HTML reports and CSV statistics
"""